### ISSUE TITLE
Windows toolchain libraries need to be updated

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/buildscripts#21]
- [x] expat 2.1.0 → 2.2.0
- [x] freetype 2.6.2 → 2.6.5
- [x] glew 1.13.0 → 2.0.0
- [x] harfbuzz 1.1.3 → 1.3.2
- [x] icu4c-56.1 → 59.1
- [x] libpng 1.6.20 → 1.6.29
- [x] libsndfile 1.0.26 → 1.0.28
- [x] libxmp-lite 4.4.1 (needs to be added)
- [x] mpg123 1.23.3 → 1.24.0
- [x] pixman 0.32.8 → 0.34.0
- [x] SDL2 2.0.4 → 2.0.5
- [x] wildmidi 0.4.1 (should be added)

**Comment by Ghabry** [comment]
Is this list still up-to-date or are some libs already updated again?
My deps.json agrees with these versions except for xmp-lite where I have 4.4.0 for some reason.

**Comment by carstene1ns** [comment]
This list should be recent. At least urlwatch tells me nothing different.

**Comment by carstene1ns** [comment]
mpg123 was updated in the meanwhile.
