### ISSUE TITLE
Migrate to "vcpkg" tool for windows toolchain

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/buildscripts#24]
vcpkg tool appears to be under development since this year and is a tool+repo by Microsoft which contains user contributed buildscripts for some libraries: https://github.com/Microsoft/vcpkg

Have to check if it supports static library builds.

So this basicly fulfills the same purpose as my powershell script but is written in CMake. :D. Does not ship all libraries (and for ICU we better build the small data file on our own).

**Comment by carstene1ns** [comment]
Looks good: https://github.com/Microsoft/vcpkg/blob/master/ports/expat/portfile.cmake

**Comment by Ghabry** [comment]
The only annoyance I'm seeing is that multithreaded builds don't work for all libs, so compiling takes ages. :(

It supports DLL builds and static builds and provides ways to compile for x86, x64 and UWP. So is excellent for our purposes 👍 .

The following packages are missing and I would need to submit a PR to the vcpkg repo:
 - speexdsp (and libsamplerate, too unfortunately, otherwise would have used this one)
 - xmp
 - wildmidi

I think I have to work on a migration to vcpkg after the summer break, makes my life much easier :D

**Comment by Ghabry** [comment]
speexdsp was added in the meanwhile.

Still missing: xmp(-lite) and wildmidi, need to submit a patch

Other problems:
 - Freetype does not depend on harfbuzz (as you know freetype must be compiled twice...)
 - Harfbuzz depends on glib which doesn't support static builds m(
 - opusfile depends on openssl (but openssl on nothing else, will test how long this takes)
 - Because of the custom data file is probably easier to build ICU manual, as we already do
 - minor: libflac (pulled in by libsndfile and sdl2 mixer) does not support UWP

Providing custom portfiles is quite easy, so most of the problems should be solvable. Harfbuzz in freetype could be upstreamed.

**Comment by Ghabry** [comment]
Submitted ports for xmplite and wildmidi
https://github.com/Microsoft/vcpkg/pull/1901
https://github.com/Microsoft/vcpkg/pull/1902

**Comment by Ghabry** [comment]
Current status of vcpkg:

1. I will keep Harfbuzz out for now and only use freetype beacuse I have compile problems when disabling glib.
2. Freetype has a useless dep on bzip2 but this is so minor that I don't see an issue in keeping it in.
3. For libsndfile, opusfile, sdl2 image and sdl2 mixer I try to upstream feature options to allow disabling of useless deps (which is libflac for sndfile, openssl for opusfile (that one is especially bad), some image and music formats.
4. Our fancy ICU patch can't be upstreamed, is too invasive ;)

**Comment by Ghabry** [comment]
Renamed it from "Evaluate" to "Migrate" because I already decided about this.

Just some status update about the usability of the packages:

No problems: zlib, libpng, expat, freetype, libmpg123, libogg, libvorbis, wildmidi, xmp-lite, pixman, speexdsp, opus, SDL2

No problems anymore (build time flag, upstream):
 - SDL2_image: tiff, webp and jpeg are optional
 - libsndfile: external-libs (ogg, vorbis, flac) are optional
 - opusfile: opusurl which pulls in openssl are optional

Not nice, but not really a problem:
 - SDL2_mixer: My patch wasn't accepted (yet), depends on libflac, mpg123, libmodplug, libvorbis of which flac and modplug are not used by us but none of them has extra dependencies, therefore: So what.

Still problematic but not important by now:
- Harfbuzz: Glib can't be disabled -> error

Needs manual patch:
 - ICU with our custom data file

Which means there are no significant issues anymore that prevent using vcpkg, everything is managed in the upstream repo now.
