### ISSUE TITLE
Latest library versions

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/buildscripts#27]
Please update using the attached spreadsheet 

[easy-sheet.ods](https://github.com/EasyRPG/buildscripts/files/6819028/easy-sheet.ods)

Library |		Version |
------|		---------|
zlib	|	1.2.12
libpng	|	1.6.37
freetype	|	2.12.1
harfbuzz	|	5.1.0
pixman	|	0.40.0
expat	|	2.4.8
libogg	|	1.3.5
libvorbis(file)	|	1.3.7
ICU	|	71.1
mpg123	|	1.30.2
libsndfile	|	1.1.0
xmp-lite	|	4.5.0
speexdsp	|	1.2.1
samplerate	|	0.2.2
wildmidi	|	0.4.4
opus	|	1.3.1
opusfile	|	0.12
fluidsynth	|	2.2.9
FluidLite	|	e19888e
fmt	|	9.1.0
json	|	3.11.2
libvpx	|	1.12.0
SDL2	|	2.24.0

**Comment by Ghabry** [comment]
table updated and windows removed, is now vcpkg maintainer problem ;)

**Comment by Ghabry** [comment]
should be up-to-date again ;)

**Comment by Ghabry** [comment]
Helper script to build the Player for testing (not including Android as this already supports Player building):

```sh
#!/bin/bash
set -e

rm -rf player
git clone https://github.com/easyrpg/player --depth=1

export BS=$PWD/easyrpg-buildscripts
cd player

# Linux
echo "=== Linux ==="
cmake . -GNinja -Bbuild-linux -DCMAKE_PREFIX_PATH=$BS/linux-static
cmake --build build-linux --target check

# Vita
echo "=== Vita ==="
export VITASDK=$BS/vita/vitasdk
cmake . -GNinja -Bbuild-vita -DPLAYER_TARGET_PLATFORM=psvita -DCMAKE_TOOLCHAIN_FILE=$VITASDK/share/vita.toolchain.cmake
cmake --build build-vita

# 3DS
echo "=== 3ds ==="
export TOOLCHAIN_DIR=$BS/3ds
pushd builds/3ds
make -j4
popd

# Wii
echo "=== Wii ==="
export TOOLCHAIN_DIR=$BS/wii
pushd builds/wii
make -j4
popd

# Switch
echo "=== Switch ==="
export TOOLCHAIN_DIR=$BS/switch
pushd builds/switch
make -j4
popd

# emscripten
echo "=== Emscripten ==="
cmake . -GNinja -Bbuild-js \
 -DCMAKE_TOOLCHAIN_FILE=$BS/emscripten/emsdk-portable/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake \
 -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=BOTH \
 -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=BOTH -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=BOTH \
 -DCMAKE_PREFIX_PATH=$BS/emscripten -DCMAKE_BUILD_TYPE=Release -DPLAYER_JS_BUILD_SHELL=ON \
 -DPLAYER_JS_OUTPUT_NAME=index
cmake --build build-js
```

**Comment by carstene1ns** [comment]
Closing for now, since it is outdated.
Maybe we can have some matrix generated by a script nowadays to show used library versions in readme.
