### ISSUE TITLE
Android: support AArch-64

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/buildscripts#29]
My tablet uses this :grin:. ABI is `arm64-v8a`.

**Comment by Ghabry** [comment]
Soon we reach the APK size limit :D

**Comment by Ghabry** [comment]
Google requires this by 2019, so we should slowly add it ;)

**Comment by fdelapena** [comment]
Due to a bug in binutils, NDK it should be updated to r16 first because it might generate broken binaries in previous versions, however this requires to update the build script to use unified headers.
r16 still supports armeabi, mips and mips64 targets, but deprecated.

**Comment by carstene1ns** [comment]
Okay, so time to drop mips support ~~~~
