### ISSUE TITLE
Support devkitPro pacman (fix buildsystem)

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/buildscripts#38]
The devkitPro team broke the update script a few days ago which means three of our scripts are broken now -_-

**Comment by Ghabry** [comment]
**WARNING** THIS IS NOT OFFICIALLY SUPPORTED BY DEVKITPRO OR WNTRMUTE, DONT ASK OR TELL HIM ABOUT THIS **WARNING**

One solution is downloading this deb file https://github.com/devkitPro/pacman/releases/download/v1.0.0/devkitpro-pacman.deb and extracting it with 7z.

Afterwards the devkitXXX stuff can be installed via:
./opt/devkitpro/pacman/bin/pacman -r $PWD --config $PWD/opt/devkitpro/pacman/etc/pacman.conf

Relevant packages (still need some extra like ctrulib):
```
dkp-linux/devkitA64 r9-1 (switch-dev)
    Toolchain for Nintendo Switch homebrew development
dkp-linux/devkitARM r48-2 (gp32-dev gba-dev nds-dev 3ds-dev)
    Toolchain for ARM based development
dkp-linux/devkitPPC r30-1 (gamecube-dev wii-dev)
    Toolchain for Nintendo Gamecube & Wii homebrew development
```
They are installed in the opt/devkitpro folder, no root permissions needed

**WARNING** THIS WAS NOT OFFICIALLY SUPPORTED BY DEVKITPRO OR WNTRMUTE, DONT ASK OR TELL HIM ABOUT THIS **WARNING**

**Comment by carstene1ns** [comment]
This is totally insane.
We only need the devkit and can build the tools and platform library anyway, so doing that is fine IMO.
We can discuss this on IRC later, but i can quickly make a PR for that.

**Comment by Ghabry** [comment]
In case somebody wants to continue working on this (I won't before vacation):

https://github.com/Ghabry/easyrpg-buildscripts/tree/pacman

3DS: sf2dlib doesn't compile anymore :/
Wii: Fails in libsndfile with
```
[...]/easyrpg-buildscripts/wii/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/8.1.0/include/ssp/stdio.h:38:10: fatal error: ssp.h: No such file or directory                          
 #include <ssp.h>
```
Switch: Compiles fine

**Comment by carstene1ns** [comment]
I have made an alternative approach, letting the user handle the devkit stuff:
https://github.com/EasyRPG/buildscripts/compare/master...carstene1ns:devkit-contra
Is just lacking some checks for required tools, i.e. 3dsxtool, but this is a general problem (we also do not test for patch or perl).

**Comment by Ghabry** [comment]
Considering that my approach doesn't fully work (when I install the official way I can compile libsndfile) this is probably the best way... good that there is pacman for fedora.

3dsxtool & co. should be reported missing by the CMake Toolchain File imo.
