### ISSUE TITLE
libmpg123 does not appear to install into the architecture-specific directories

### ISSUE THREAD

**Issue by sorlok** [EasyRPG/buildscripts#79]
Hi all,

I checked out and ran the Android build locally, but got the following error:
```
 Android NDK: ERROR:jni/deps/Android.mk:mpg123: LOCAL_SRC_FILES points to a missing file
 Android NDK: Check that /home/sethhetu/source/EasyRpgBuildScripts/android/armeabi-v7a-toolchain/lib/libmpg123.a exists  or that its path is correct
```

The files in question exist in "lib" and "include" --they just weren't copied into "armeabi-v7a-toolchain/lib", "armeabi-v7a-toolchain/include", etc. I can sort of work around this with the following:

```
/usr/bin/install -c lib/libmpg123.a $HOME/source/EasyRpgBuildScripts/android/armeabi-v7a-toolchain/lib/libmpg123.a
chmod 644 $HOME/source/EasyRpgBuildScripts/android/armeabi-v7a-toolchain/lib/libmpg123.a
arm-linux-androideabi-ranlib $HOME/source/EasyRpgBuildScripts/android/armeabi-v7a-toolchain/lib/libmpg123.a

cp include/fmt123.h armeabi-v7a-toolchain/include/
cp include/mpg123.h armeabi-v7a-toolchain/include/
```

...and similar for the other architectures. This seems like the wrong way to do it, though, and eventually fails with:
```
/home/sethhetu/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /home/sethhetu/source/EasyRpgBuildScripts/android/armeabi-v7a-toolchain/lib/libmpg123.a: no archive symbol table (run ranlib)
```

This seems like it would be fairly easy to fix by someone who knows the build system, so I'm filing this report here. If it's not obvious how to fix this, I can probably dig in further.

Thanks.

**Comment by carstene1ns** [comment]
Ah, sorry, that was my fault. I blindly assumed the $PLATFORM_PREFIX would always be the $WORKSPACE, but of course for android this is wrong :/

You need to replace it in these lines:
https://github.com/EasyRPG/buildscripts/blob/cc056a9277daf656a1a1d151e31ea994053fb9b5/shared/common.sh#L122-L125

**Comment by sorlok** [comment]
Looks good with the replacement fix, thanks!

**Comment by sorlok** [comment]
(Let me know if you want me to file a PR for this)

**Comment by carstene1ns** [comment]
If you want to, I appreciate it, otherwise will do it in a few hours.

**Comment by sorlok** [comment]
Filed PR #80

**Comment by carstene1ns** [comment]
Thank you!
