### ISSUE TITLE
DHB_NO_MMAP needed in 4_build_liblcf.sh for android

### ISSUE THREAD

**Issue by sorlok** [EasyRPG/buildscripts#82]
When building the android build, I received an error about the build environment not matching due to -DHB_NO_MMAP. I was able to fix it by changing line 39 of 4_build_liblcf.sh from:
`export CXXFLAGS=$CFLAGS`
...to:
`export CXXFLAGS="$CFLAGS -DHB_NO_MMAP"`

As far as I can tell, someone added -DHB_NO_MMAP to some higher-level make file and never updated this script.

Actual build error is:
```
**** Building liblcf ****
configure: loading cache /home/sethhetu/source/EasyRpgBuildScripts/android/armeabi-v7a-toolchain/config.cache
configure: error: `CXXFLAGS' has changed since the previous run:
configure:   former value:  `-g0 -O2 -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3 -DHB_NO_MMAP'
configure:   current value: `-g0 -O2 -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3'
configure: error: in `/home/sethhetu/source/EasyRpgBuildScripts/android/liblcf':
configure: error: changes in the environment can compromise the build
configure: error: run `make distclean' and/or `rm /home/sethhetu/source/EasyRpgBuildScripts/android/armeabi-v7a-toolchain/config.cache' and start over
```

**Comment by Ghabry** [comment]
I have really no idea why mmap is broken on Android...

**Comment by sorlok** [comment]
Honestly no idea, but the flag's clearly set in an earlier script:
```
./android/2_build_toolchain.sh:	export CXXFLAGS="$CFLAGS -DHB_NO_MMAP"
```

...so might as well keep it in sync for 4_build_liblcf.sh?

Also, is this somehow not failing for everyone else?

**Comment by Ghabry** [comment]
The 4 and 5 script are just for convenience because building for Android sucks so much. (good luck figuring this mess out)

On Jenkins we use a different script.

Your fix is fine, was just me complaining about Android ;).

**Comment by sorlok** [comment]
Created PR 84 to fix this.
