### ISSUE TITLE
Player crashes on startup (autoResumeAudioContext is not defined)

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/buildscripts#83]
Player crashes in newer master and pull request builds since the rebuild after adding fluidlite:

    Uncaught ReferenceError: autoResumeAudioContext is not defined

This function does not seem defined on upstream SDL2, but in the Emscripten SDL2 port, which improves the previous audio autoplay workaround in Chromium. Current buildscript uses emscripten 1.39.5, which is before this change, and the SDL2 port has no sticked release.

Upgrading emscripten to 2.0.1 should fix this issue.

**Comment by Ghabry** [comment]
this can't become worse now so I will try pinning a newer emscripten version...

**Comment by Ghabry** [comment]
I attempted an update locally.

I use emscripten 2.0.2 and ``-s EXTRA_EXPORTED_RUNTIME_METHODS="['autoResumeAudioContext']"`` but I still get this error.

**Comment by Ghabry** [comment]
Filed an issue because I'm out of ideas: https://github.com/emscripten-core/emscripten/issues/12063
